#!/bin/bash
#
#load the module
source /apps/profiles/modules_asax.sh.dyn

module load stringtie/2.2.1

GENOME=/home/usaocb001/perezjh_research/Data/References_genomes/Zebra_Finch_17June2024/GCF_003957565.2/GCF_003957565.2_bTaeGut1.4.pri_genomic.fna
ANNO=/home/usaocb001/perezjh_research/Data/References_genomes/Zebra_Finch_17June2024/GCF_003957565.2/genomic.gff

# Set the directory path where the BAM files are located
directory="/scratch/usaocb001/NAME/05_HiSat2"
directory1="/scratch/usaocb001/NAME/06_StringTie2"

cd "$directory"

    # Set the output GTF file name
    output_csv="$directory1/NAME.gtf"

    # Set the output abundance table file name
    output_abund_table="$directory1/NAME_abund.tab"

    # Count reads within venom gene peaks using HTSeq-count
    stringtie -p 24 -G $ANNO -e -o $output_csv -B -A $output_abund_table NAME_VG_Sorted.bam
